### ISSUE TITLE
make docker-running fails - Ubuntu 18.04 

### ISSUE THREAD

**Issue by jackinloadup** [DrupalStand/drupal-dev-docker#36]
returns ```Error: No such object: govcon-2018-drupal-{db,php,web}``` the expansion doesn't work. 

Make version
arch 4.2.1
ubuntu 4.1

Bash version
arch 4.4.23
ubuntu 4.4.19

Running make in a zsh shell didn't help

**Comment by jackinloadup** [comment]
Relates to #40

**Comment by smfsh** [comment]
Doesn't seem to happen anymore. Resolved I guess?

**Comment by stevenlafl** [comment]
Happens in WSL, Debian.
