### ISSUE TITLE
Repository name must be lowercase

### ISSUE THREAD

**Issue by subtera745** [DrupalStand/drupal-dev-docker#43]
If cloning repo to system with a name that starts with an uppercase letter, on init it will fail. 

Building db                                                        
ERROR: invalid reference format: repository name must be lowercase

**Comment by jackinloadup** [comment]
@subtera745 There is likely somewhere in the Makefile or other build process that needs to have the name converted to lowercase.

**Comment by smfsh** [comment]
fixed 0f5d5951d198f9ed902007e80f518e75a8a3ccf7
